# Generated by Django 4.2.23 on 2025-11-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enseignant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_naissance", models.DateField()),
                ("lieu_naissance", models.CharField(max_length=150)),
                ("matiere", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_naissance", models.DateField()),
                ("lieu_naissance", models.CharField(max_length=150)),
                ("niveau_etude", models.CharField(max_length=100)),
                ("classe", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=15)),
            ],
        ),
    ]
