# Generated by Django 4.2.23 on 2025-12-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enseignant",
            name="photo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="etudiant",
            name="photo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
