# Generated by Django 4.2.23 on 2025-12-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_enseignant_photo_etudiant_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("etudiant", "Étudiant"),
                            ("enseignant", "Enseignant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("personne_id", models.IntegerField()),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_scan", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
