# Generated by Django 4.2.27 on 2025-12-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_enseignant_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enseignant",
            name="photo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
