# Generated by Django 4.2.27 on 2025-12-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_enseignant_photo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScanHistory",
        ),
    ]
