# Generated by Django 4.2.27 on 2025-12-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_scanhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enseignant",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="enseignants/"),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="etudiants/"),
        ),
    ]
