# Generated by Django 4.2.27 on 2026-02-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_enseignant_id_alter_etudiant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnes/')),
            ],
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
