# Generated by Django 4.2.27 on 2026-02-25 21:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_personne_alter_enseignant_id_alter_etudiant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaiementEnseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, help_text="Montant du paiement", max_digits=10
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Date du paiement"
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements_salaire",
                        to="api.enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Enseignant",
                "verbose_name_plural": "Paiements Enseignants",
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.CreateModel(
            name="AssuranceEtudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total de l'assurance",
                        max_digits=10,
                    ),
                ),
                (
                    "montant_paye",
                    models.DecimalField(
                        decimal_places=2, help_text="Montant déjà payé", max_digits=10
                    ),
                ),
                (
                    "montant_restant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant restant à payer",
                        max_digits=10,
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Date du paiement"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("complet", "Payé complètement"),
                            ("partiel", "Payé partiellement"),
                            ("impaye", "Non payé"),
                        ],
                        default="impaye",
                        max_length=20,
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements_assurance",
                        to="api.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assurance Étudiant",
                "verbose_name_plural": "Assurances Étudiants",
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.CreateModel(
            name="AssuranceEnseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total de l'assurance",
                        max_digits=10,
                    ),
                ),
                (
                    "montant_paye",
                    models.DecimalField(
                        decimal_places=2, help_text="Montant déjà payé", max_digits=10
                    ),
                ),
                (
                    "montant_restant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant restant à payer",
                        max_digits=10,
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Date du paiement"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("complet", "Payé complètement"),
                            ("partiel", "Payé partiellement"),
                            ("impaye", "Non payé"),
                        ],
                        default="impaye",
                        max_length=20,
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements_assurance",
                        to="api.enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assurance Enseignant",
                "verbose_name_plural": "Assurances Enseignants",
                "ordering": ["-date_paiement"],
            },
        ),
    ]
