# Generated by Django 4.2.27 on 2026-02-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_paiementenseignant_assuranceetudiant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiementenseignant",
            name="annee",
            field=models.IntegerField(
                blank=True, help_text="Année du paiement", null=True
            ),
        ),
        migrations.AddField(
            model_name="paiementenseignant",
            name="mois",
            field=models.IntegerField(
                blank=True, help_text="Mois du paiement (1-12)", null=True
            ),
        ),
        migrations.AddField(
            model_name="paiementenseignant",
            name="salaire_prevu",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Salaire prévu", max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="paiementenseignant",
            name="salaire_restant",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Salaire restant après paiement",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="paiementenseignant",
            name="montant",
            field=models.DecimalField(
                decimal_places=2, help_text="Montant payé", max_digits=10
            ),
        ),
    ]
