# Generated by Django 4.2.27 on 2026-02-27 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_paiementenseignant_annee_paiementenseignant_mois_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matiere", models.CharField(max_length=100)),
                ("note", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "coefficient",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4),
                ),
                (
                    "type_examen",
                    models.CharField(
                        choices=[
                            ("devoir", "Devoir"),
                            ("examen", "Examen"),
                            ("rattrapage", "Rattrapage"),
                            ("tp", "TP"),
                        ],
                        default="devoir",
                        max_length=20,
                    ),
                ),
                (
                    "semestre",
                    models.IntegerField(
                        choices=[(1, "Semestre 1"), (2, "Semestre 2")], default=1
                    ),
                ),
                (
                    "date_saisie",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_saisies",
                        to="api.enseignant",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="api.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "ordering": ["-date_saisie"],
            },
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("matiere", models.CharField(max_length=100)),
                (
                    "type_absence",
                    models.CharField(
                        choices=[
                            ("absence", "Absence"),
                            ("retard", "Retard"),
                            ("present", "Présent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="api.etudiant",
                    ),
                ),
            ],
        ),
    ]
