# Generated by Django 4.2.27 on 2026-03-06 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_note_absence"),
    ]

    operations = [
        migrations.AddField(
            model_name="enseignant",
            name="date_creation",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
