# Generated by Django 4.2.27 on 2026-03-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_enseignant_date_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enseignant",
            name="date_creation",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
